services:
  - type: web
    name: movie-booking-review-demo
    runtime: python
    rootDir: .
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python create_superuser.py"
    startCommand: "python manage.py migrate && python create_superuser.py && gunicorn jishitha.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 2
